import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Main from "@/components/Main";
import { Divider } from "@mui/joy";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { ToastContainer } from "react-toastify";

type HomeProps = {
    authUser: string;
    authPass: string;
    apiKey: string;
};

const Home: NextPage<HomeProps> = ({ authUser, authPass, apiKey }) => {
    return (
        <>
            <Head>
                <title>AU Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Divider />
            <Main />
            <Divider />
            <Footer authUser={authUser} authPass={authPass} apiKey={apiKey} />
            <ToastContainer />
        </>
    );
};

/* export const getServerSideProps: GetServerSideProps = async (ctx) => {
    console.log("[code]: Server side props called...");
    console.log(
        `[code]: ${process.env.AUTH_USER} | ${process.env.AUTH_PASS} | ${process.env.API_KEY}`
    );

    return {
        props: {
            authUser: process.env.AUTH_USER,
            authPass: process.env.AUTH_PASS,
            apiKey: process.env.API_KEY,
        },
    };
}; */

export default Home;
